[General]
loglevel = notify
dns-server = 223.5.5.5, 114.114.114.114, 8.8.8.8
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
exclude-simple-hostnames = true
ipv6 = false

[Proxy]
DIRECT = direct
JMS-c81s3 = vmess, c81s3.portablesubmarines.com, 16001, username=b8b8c60e-48c2-44a7-9dff-c4154100af8d, tls=true, tls13=true, skip-cert-verify=false, sni=c81s3.portablesubmarines.com, tfo=true, vmess-aead=true
JMS-c81s4 = vmess, c81s4.portablesubmarines.com, 16001, username=b8b8c60e-48c2-44a7-9dff-c4154100af8d, tls=true, tls13=true, skip-cert-verify=false, sni=c81s4.portablesubmarines.com, tfo=true, vmess-aead=true
JMS-c81s5 = vmess, c81s5.portablesubmarines.com, 16001, username=b8b8c60e-48c2-44a7-9dff-c4154100af8d, tls=true, tls13=true, skip-cert-verify=false, sni=c81s5.portablesubmarines.com, tfo=true, vmess-aead=true
JMS-c81s801 = vmess, c81s801.portablesubmarines.com, 16001, username=b8b8c60e-48c2-44a7-9dff-c4154100af8d, tls=true, tls13=true, skip-cert-verify=false, sni=c81s801.portablesubmarines.com, tfo=true, vmess-aead=true

[Proxy Group]
🚀 节点选择 = select, ♻️ 自动选择, JMS-c81s3, JMS-c81s4, JMS-c81s5, JMS-c81s801, DIRECT
♻️ 自动选择 = url-test, JMS-c81s3, JMS-c81s4, JMS-c81s5, JMS-c81s801, url=http://www.gstatic.com/generate_204, interval=300, tolerance=50

[Rule]
DOMAIN-SUFFIX,local,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
GEOIP,CN,DIRECT
FINAL,🚀 节点选择
